### ISSUE TITLE
Add an "Edit on GitHub" button

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-developer-documentation#102] opened 2018-04-18 16:46 UTC
Should we add an "Edit on GitHub" button/link like we do on docs.mattermost.com, so it's obvious where to go to propose changes?

**Comment by jasonblais** [comment] 2018-06-21 13:21
Closing as duplicate of https://github.com/mattermost/mattermost-developer-documentation/issues/25

**Closed by jasonblais** 2018-06-21 13:21 UTC
