### ISSUE TITLE
my build dot work

### ISSUE THREAD

**Issue by elvisfromsouth** [mattermost/mattermost-developer-documentation#199] opened 2018-12-05 13:39 UTC
i build my android apk (via `make build-android`), but i see only spash screen

```
java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
   at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
   at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
   at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
   at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1116)
   at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:117)
   at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
   at java.lang.Thread.run(Thread.java:818)
```

also
i try `make unsigned-android`, but i cant install apk

**Comment by hanzei** [comment] 2018-12-05 13:54
Closing this one as its a duplicate of https://github.com/mattermost/mattermost-mobile/issues/2420

**Closed by hanzei** 2018-12-05 13:54 UTC
